name             'jtcbg'
maintainer       'Joshua Timberman'
maintainer_email 'cookbooks@housepub.org'
license          'Apache 2 License'
description      'Generates Chef code for Chef DK'
long_description 'Generates Chef code for Chef DK'
version          '0.2.0'
